hmrc/tariff-classification-frontend

app/uk/gov/hmrc/tariffclassificationfrontend/connector/BindingTariffClassificationConnector.scala, app/uk/gov/hmrc/tariffclassificationfrontend/views/case_not_found.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/advanced_search_results.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/nav_search.scala.html, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/AdvancedSearchResultsViewSpec.scala
BAU - Add ids and fix description behaviour
=> BAU - Add ids and fix description behaviour

app/uk/gov/hmrc/tariffclassificationfrontend/views/confirm_reject_case.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/confirm_suppress_case.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/refer_case.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/reject_case.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/reopen_case.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/suppress_case.scala.html
=> DIT-375 remove link for `Add a note`

app/uk/gov/hmrc/tariffclassificationfrontend/controllers/AppealCaseController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/controllers/ExtendedUseCaseController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/controllers/ReviewCaseController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/controllers/StatusChangeAction.scala, app/uk/gov/hmrc/tariffclassificationfrontend/controllers/StatusUpdateController.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/AppealCaseControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/ExtendedUseCaseControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/ReviewCaseControllerSpec.scala
The Appeal, Review & Extended Use Status Change controllers have very similar logic. We could pull this out into a trait. Let me know your thoughts
=> BAU - Pull out common logic into trait

app/uk/gov/hmrc/tariffclassificationfrontend/controllers/CaseController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/models/AppealStatus.scala, app/uk/gov/hmrc/tariffclassificationfrontend/models/Queues.scala, app/uk/gov/hmrc/tariffclassificationfrontend/models/ReviewStatus.scala, app/uk/gov/hmrc/tariffclassificationfrontend/service/QueuesService.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/CaseControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/ReassignCaseControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/forms/UploadAttachmentFormTest.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/ActivityDetailsViewSpec.scala
Small attempts at increasing code coverage
=> Refactor queue name map

app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/advanced_search_results.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/thumbnail.scala.html, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/AdvancedSearchResultsViewSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/ThumbnailViewSpec.scala
Created new 'thumbnail' partial view which includes anchor tag opening image in new window/tab
This view can potentially be re-used to display attachment thumbnails on the 'attachments' tab
=> DIT-904 - thumbnail open new tab

app/uk/gov/hmrc/tariffclassificationfrontend/controllers/SearchController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/views/SearchTab.scala, app/uk/gov/hmrc/tariffclassificationfrontend/views/advanced_search.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/advanced_search_results_tabs.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/thumbnail.scala.html, conf/app.routes, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/SearchControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/AdvancedSearchViewSpec.scala
=> DIT-902 fixes

app/uk/gov/hmrc/tariffclassificationfrontend/connector/BindingTariffClassificationConnector.scala, app/uk/gov/hmrc/tariffclassificationfrontend/controllers/CaseController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/controllers/SampleController.scala, app/uk/gov/hmrc/tariffclassificationfrontend/service/EventsService.scala, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/activity_details_events_table.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/sample/sample_details.scala.html, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/sample/sample_status_events_table.scala.html, test/it/uk/gov/hmrc/tariffclassificationfrontend/CaseSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/connector/BindingTariffClassificationConnectorSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/CaseControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/controllers/SampleControllerSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/service/EventsServiceSpec.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/sample/SampleDetailsViewSpec.scala
=> Show filtered activities on activity tab, and sample tab

app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/ShowActions.scala, app/uk/gov/hmrc/tariffclassificationfrontend/views/partials/liabilities/liability_actions.scala.html, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/ShowActionsTest.scala, test/unit/uk/gov/hmrc/tariffclassificationfrontend/views/partials/liabilities/LiabilityActionsViewSpec.scala, test/util/uk/gov/tariffclassificationfrontend/utils/CaseQueueBuilder.scala
This is part of the "not taking ownership" journey
=> DIT-1050 add permission checks to "action" links 

app/config/AppConfig.scala, app/controllers/CaseController.scala, app/controllers/RequestActions.scala, app/controllers/v2/LiabilityController.scala, app/models/viewmodels/C592ViewModel.scala, app/models/viewmodels/CaseHeaderViewModel.scala, app/models/viewmodels/CaseStatusViewModel.scala, app/models/viewmodels/LiabilityViewModel.scala, app/views/v2/case_heading.scala.html, app/views/v2/liability_view.scala.html, conf/application.conf, conf/messages, test/unit/config/AppConfigSpec.scala, test/unit/controllers/CaseControllerSpec.scala, test/unit/controllers/SuccessfulAuthenticatedAction.scala, test/unit/controllers/v2/LiabilityControllerSpec.scala, test/unit/models/viewmodels/LiabilityViewModelSpec.scala, test/util/utils/Cases.scala
To run: ```sbt -Dtoggle.new-liability-details=true run```
=> DIT-1218 Added toggle for LiabilityController v2 

app/config/AppConfig.scala, app/controllers/AuthenticatedAction.scala, test/unit/controllers/AuthenticatedActionSpec.scala
This reverts commit 90eafd7bb0c7162744b4b83e19518d700b68f6c1.
=> Revert "fix the port for sign in url (#303)"

app/views/advanced_search.scala.html, app/views/appeal_change_status.scala.html, app/views/appeal_choose_status.scala.html, app/views/appeal_choose_type.scala.html, app/views/cancel_ruling.scala.html, app/views/change_case_status.scala.html, app/views/change_extended_use_status.scala.html, app/views/create_liability.scala.html, app/views/edit_liability_decision.scala.html, app/views/forms/components/input_date.scala.html, app/views/forms/components/input_text.scala.html, app/views/forms/components/input_textarea.scala.html, app/views/forms/liability_sending_sample_form.scala.html, app/views/forms/sample_return_form.scala.html, app/views/forms/sample_status_form.scala.html, app/views/forms/search_box.scala.html, app/views/forms/select_queue_form.scala.html, app/views/helpers/FormWithCSRF.scala.html, app/views/partials/liabilities/liability_actions.scala.html, app/views/partials/liabilities/liability_details_edit.scala.html, app/views/partials/reopen_case_button.scala.html, app/views/partials/reports/referral_report_criteria.scala.html, app/views/partials/reports/sla_report_criteria.scala.html, app/views/refer_case.scala.html, app/views/reject_case.scala.html, app/views/release_or_suppress.scala.html, app/views/remove_attachment.scala.html, app/views/suppress_case.scala.html, app/views/suspend_case.scala.html, app/views/v2/remove_attachment.scala.html
Also fixes DIT-1894
Fixes:
- text inputs
- textareas
- date inputs
=> DIT-1892 Ensure aria only present when required

app/views/partials/attachments_details.scala.html, app/views/partials/case_heading.scala.html, app/views/partials/statuses/case_status.scala.html, app/views/ruling_details_edit.scala.html, app/views/v2/case_heading.scala.html, app/views/v2/liability_details_edit.scala.html, test/unit/views/partials/statuses/CaseStatusViewSpec.scala
Edit details currently H1 and it should be H2
Upload new files currently H2 and it should be H3
Add 'LIVE' status for user
tabindex doesn't wok on BTI complete cases
=> DIT 2289 fixed some issues Operational service from an accessibility point of view

app/connector/BindingTariffClassificationConnector.scala, app/connector/DataCacheConnector.scala, app/connector/EmailConnector.scala, app/connector/FileStoreConnector.scala, app/connector/PdfGeneratorServiceConnector.scala, app/connector/RulingConnector.scala, app/connector/StrideAuthConnector.scala, app/metrics/HasMetrics.scala, test/it/integration/IntegrationTest.scala, test/unit/base/SpecBase.scala, test/unit/connector/BindingTariffClassificationConnectorSpec.scala, test/unit/connector/EmailConnectorSpec.scala, test/unit/connector/FileStoreConnectorSpec.scala, test/unit/connector/MongoCacheConnectorSpec.scala, test/unit/connector/PdfGeneratorServiceConnectorSpec.scala, test/unit/connector/RulingConnectorTest.scala, test/unit/metrics/HasMetricsSpec.scala, test/util/utils/TestMetrics.scala
This PR adds metrics timers to each of the connectors that we use in the classification frontend
=> DIT-2287 add connector metrics to the classification frontend

app/views/partials/application_details.scala.html, app/views/partials/case_trader.scala.html
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/68
=> DIT-2115 | Use pre-wrap class for fields for migrated BTI's

app/models/Attachment.scala, app/models/StoredAttachment.scala, test/unit/controllers/SearchControllerSpec.scala, test/unit/models/StoredAttachmentTest.scala, test/unit/service/FileStoreServiceSpec.scala, test/unit/views/partials/AdvancedSearchResultsViewSpec.scala, test/unit/views/partials/EditRulingDetailsViewSpec.scala, test/unit/views/partials/ThumbnailViewSpec.scala, test/unit/views/partials/ruling/RulingDetailsViewSpec.scala, test/util/utils/Cases.scala
Supporting PR for https://github.com/hmrc/binding-tariff-data-transformation/pull/82
=> DIT-2121 | Added description to attachment model

app/models/Application.scala, test/util/utils/Cases.scala
To support https://github.com/hmrc/binding-tariff-data-transformation/pull/112
=> DIT-2575 | Updating liabilities application model

app/service/CasesService.scala, app/views/components/cases_cards.scala.html, test/unit/views/components/CaseCardsViewSpec.scala
=> DIT-2559 | Assigned to me count

app/models/Operator.scala, app/views/operator_dashboard_classification.scala.html
will need to be merged after the backend changes: https://github.com/hmrc/binding-tariff-classification/pull/171
=> DIT-2707 | update operator model with new fields for users

app/assets/stylesheets/colours.scss, app/audit/AuditService.scala, app/connector/BindingTariffClassificationConnector.scala, app/controllers/v2/ManageUserController.scala, app/models/Operator.scala, app/models/forms/v2/RemoveUserForm.scala, app/service/UserService.scala, app/views/partials/users/cannot_delete_user.scala.html, app/views/partials/users/confirm_delete_user.scala.html, app/views/partials/users/delete_user_heading.scala.html, app/views/partials/users/done_delete_user.scala.html, app/views/partials/users/user_details.scala.html, app/views/partials/users/view_user.scala.html, conf/app.routes, conf/messages, test/unit/connector/BindingTariffClassificationConnectorSpec.scala, test/unit/controllers/v2/ManageUserControllerSpec.scala, test/unit/service/UserServiceSpec.scala, test/unit/views/partials/users/CannotDeleteUserViewSpec.scala, test/unit/views/partials/users/ConfirmDeleteUserViewSpec.scala
Do not merge before DIT-2691
Created views for a confirmation page and the "cases must be moved" page and a controller endpoint to post the confirmation to and delete the user.
=> Dit 2695 - delete user journey

app/models/reporting/Report.scala, test/unit/controllers/ReportingControllerSpec.scala
Needs to be merged after: https://github.com/hmrc/tariff-classification-frontend/pull/519
=> DIT-2831 | predefined reports for new and open cases

app/models/reporting/Report.scala, app/views/managementtools/report_tab_view.scala.html, test/unit/controllers/ReportingControllerSpec.scala
covers ticket https://jira.tools.tax.service.gov.uk/browse/DIT-2836
=> DIT-2836 - open cases in queues

app/audit/AuditService.scala, app/controllers/SampleController.scala, app/controllers/SampleWhoSendingController.scala, app/models/Event.scala, app/models/SampleSend.scala, app/models/forms/SampleSendForm.scala, app/models/viewmodels/SampleStatusTabViewModel.scala, app/service/CasesService.scala, app/utils/JsonFormatters.scala, app/views/change_sample_send.scala.html, app/views/forms/sample_send_form.scala.html, app/views/partials/liabilities/sample/sample_details_liability.scala.html, app/views/partials/liabilities/sample/sample_status_events_table.scala.html, app/views/partials/sample/sample_details_correspondence.scala.html, conf/app.routes, conf/messages, test/it/integration/AppealCaseSpec.scala, test/it/integration/CaseSpec.scala, test/it/integration/LiabilitySpec.scala, test/it/integration/SearchSpec.scala, test/unit/audit/AuditServiceTest.scala, test/unit/controllers/SampleWhoSendingControllerSpec.scala, test/unit/models/forms/SampleSendFormTest.scala, test/unit/service/CasesService_UpdateSampleWhoSendingSpec.scala, test/unit/views/partials/correspondence/SampleDetailsViewSpec.scala, test/unit/views/partials/liabilities/status/SampleDetailsViewSpec.scala, test/unit/views/v2/CorrespondenceViewSpec.scala, test/unit/views/v2/LiabilityViewSpec.scala, test/unit/views/v2/MiscellaneousViewSpec.scala
Needs to be merged after the back end changes:
https://github.com/hmrc/binding-tariff-classification/pull/183
=> DIT-1815 | who is sending the sample functionality 

app/audit/AuditService.scala, app/controllers/v2/MoveCasesController.scala, app/service/CasesService.scala, test/unit/audit/AuditServiceTest.scala
audit-event-move-case change audit payload to include case references
audit-event-move-case added operator updating field to audit payload
=> audit-event-move-cases-2

app/views/v2/atar_view.scala.html
Reverts hmrc/tariff-classification-frontend#557
=> Revert "DIT-2773: Amended code in ATaR view to only display Keyword and Rulin…"

repository.yaml
=> DDCE-3000 - delete leakDetectionExemptions

app/views/appeal_choose_type.scala.html, app/views/change_case_status.scala.html, app/views/partials/users/atar_table.scala.html, app/views/partials/users/correspondence_table.scala.html, app/views/partials/users/liability_table.scala.html, app/views/partials/users/misc_table.scala.html, app/views/release_or_suppress.scala.html
DDCE-2586 - ET fixes for radio buttons and checkbox error summary links
=> DDCE-2586 - ET fixes for radio buttons and checkbox error summary links

app/config/AppConfig.scala, conf/application.conf, test/config/AppConfigSpec.scala
removed both reportAProblemPartialUrl  and reportAProblemNonJSUrl and tests
=> DDCE-4792 Remove references from the ajax route

app/service/CasesService.scala
Ensured file upload is completed
=> DDCE-6060 Ensured file upload is completed

conf/application.conf, project/AppDependencies.scala
=> binding-tariff-ruling - Implement GOV.UK Rebrand
